baseURL = 'https://midnordic.github.io/music-master'
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
title = 'Music Master'
theme = 'musicmaster'

[params]
  description = "Music Master is a powerful audio tool that puts sound in your hands and unleashes your creativity. Built for Game Masters."
  author = "Midnordic"
  discord_url = 'https://discord.gg/p3TraAhmJu'

[params.languageIcons]
  en = "images/english.png"
  pl = "images/polish.png"
  
[menu]
  [[menu.main]]
    name = "nav_home"    
    weight = 10
    [menu.main.params]
    relPage = ""

  [[menu.main]]
    name = "nav_docs"    
    weight = 20
    [menu.main.params]
    relPage = "docs"

  [[menu.main]]
    name = "nav_blog"    
    weight = 25
    [menu.main.params]
    relPage = "blog"

  [[menu.main]]
    name = "nav_beta"    
    weight = 30
    [menu.main.params]
    relPage = "#beta"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1    
  [languages.pl]
    languageName = "Polish"
    weight = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.parser.attribute]      
      block = true
      title = true
	  
[caches]
  [caches.images]
    dir = ':cacheDir/images'